# Generated by Django 4.1.7 on 2023-02-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="удалено"),
        ),
    ]
