# Generated by Django 4.1.7 on 2023-02-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0002_categories_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="category",
            field=models.CharField(
                choices=[
                    ("Other", "Разное"),
                    ("Phones", "Смартфоны"),
                    ("Laptops", "Ноутбуки"),
                ],
                default="Other",
                max_length=100,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.TextField(
                blank=True, max_length=2000, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="title",
            field=models.CharField(
                help_text="Наименование", max_length=100, verbose_name="Наименование"
            ),
        ),
        migrations.DeleteModel(
            name="Categories",
        ),
    ]
