# Generated by Django 4.1.7 on 2023-02-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0003_alter_products_category_alter_products_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="category",
            field=models.CharField(
                choices=[
                    ("other", "Разное"),
                    ("phones", "Смартфоны"),
                    ("laptops", "Ноутбуки"),
                ],
                default="other",
                max_length=100,
                verbose_name="Category",
            ),
        ),
    ]
