# Generated by Django 4.1.7 on 2023-02-27 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0004_alter_products_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="balance",
            field=models.IntegerField(
                default=None,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Остаток",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.TextField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Ссылка на изображение",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=7, verbose_name="Цена"
            ),
        ),
    ]
